//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtributosCloset
    {
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public Nullable<double> ValorMaximo { get; set; }
        public Nullable<double> ValorMinimo { get; set; }
        public string Valores { get; set; }
    }
}
