//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Closet
    {
        public int IdMueble { get; set; }
        public int Alto_Pared { get; set; }
        public int Largo_Pared { get; set; }
        public int Ancho_Pared { get; set; }
        public int Distancia_Repisa { get; set; }
        public double Largo_Cajones { get; set; }
        public int Altura_Cajones { get; set; }
        public int Filas_de_Cajones { get; set; }
        public int Largo_Entrepaños { get; set; }
        public int Columnas_de_Entrepaños { get; set; }
        public int Filas_de_Entrepaños { get; set; }
        public string Color_Repisa { get; set; }
        public string Color_Cajones { get; set; }
        public string Color_Entrepaños { get; set; }
    
        public virtual Mueble Mueble { get; set; }
    }
}
