//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Closet
    {
        public int IdMueble { get; set; }
        public int Alto_Pared { get; set; }
        public int Largo_Pared { get; set; }
        public int Ancho_Pared { get; set; }
        public int Distancia_Repisa { get; set; }
        public double Largo_Cajones { get; set; }
        public int Altura_Cajones { get; set; }
        public int Filas_de_Cajones { get; set; }
        public int Largo_Entrepaños { get; set; }
        public int Columnas_de_Entrepaños { get; set; }
        public int Filas_de_Entrepaños { get; set; }
        public string Color_Repisa { get; set; }
        public string Color_Cajones { get; set; }
        public string Color_Entrepaños { get; set; }
    
        public virtual Mueble Mueble { get; set; }
    }
}
