//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacion
    {
        public int IdOrden { get; set; }
        public string CotizacionPDF { get; set; }
        public string RutaModelosPDF { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaeEntrega { get; set; }
        public int IdCliente { get; set; }
        public Nullable<int> IdMuebleTipo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
