//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CG2019Entities : DbContext
    {
        public CG2019Entities()
            : base("name=CG2019Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Closet> Closet { get; set; }
        public virtual DbSet<Cotizacion> Cotizacion { get; set; }
        public virtual DbSet<Lavadero> Lavadero { get; set; }
        public virtual DbSet<Lino> Lino { get; set; }
        public virtual DbSet<Mueble> Mueble { get; set; }
        public virtual DbSet<MuebleRopas> MuebleRopas { get; set; }
        public virtual DbSet<MuebleTV> MuebleTV { get; set; }
        public virtual DbSet<Vestier> Vestier { get; set; }
    
        public virtual ObjectResult<Buscar_Mueble_Con_IdCotizacion_Result> Buscar_Mueble_Con_IdCotizacion(Nullable<int> idCotizacion)
        {
            var idCotizacionParameter = idCotizacion.HasValue ?
                new ObjectParameter("IdCotizacion", idCotizacion) :
                new ObjectParameter("IdCotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Buscar_Mueble_Con_IdCotizacion_Result>("Buscar_Mueble_Con_IdCotizacion", idCotizacionParameter);
        }
    
        public virtual ObjectResult<Buscar_Mueble_Con_IdCotizacion_Cliente_Result> Buscar_Mueble_Con_IdCotizacion_Cliente(Nullable<int> idCotizacionCl)
        {
            var idCotizacionClParameter = idCotizacionCl.HasValue ?
                new ObjectParameter("IdCotizacionCl", idCotizacionCl) :
                new ObjectParameter("IdCotizacionCl", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Buscar_Mueble_Con_IdCotizacion_Cliente_Result>("Buscar_Mueble_Con_IdCotizacion_Cliente", idCotizacionClParameter);
        }
    }
}
