//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lavadero
    {
        public int IdMueble { get; set; }
        public int Alto { get; set; }
        public int Largo { get; set; }
        public int Ancho { get; set; }
        public int Niveles { get; set; }
        public int Columnas { get; set; }
        public int NumPuertas { get; set; }
        public int Espesor { get; set; }
        public int AltSobrePiso { get; set; }
        public double DistanciaNivel { get; set; }
    
        public virtual Mueble Mueble { get; set; }
    }
}
