//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lavadero
    {
        public int IdMueble { get; set; }
        public int Alto { get; set; }
        public int Largo { get; set; }
        public int Ancho { get; set; }
        public int Niveles { get; set; }
        public int Columnas { get; set; }
        public int NumPuertas { get; set; }
        public int Espesor { get; set; }
        public int AltSobrePiso { get; set; }
        public double DistanciaNivel { get; set; }
    
        public virtual Mueble Mueble { get; set; }
    }
}
