//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuebleTV
    {
        public int IdMueble { get; set; }
        public int Alto { get; set; }
        public int Largo { get; set; }
        public int Ancho { get; set; }
        public int NumSeparaciones { get; set; }
        public int NumSeparacionesConPuerta { get; set; }
        public int Entrepaños { get; set; }
        public string Color { get; set; }
    
        public virtual Mueble Mueble { get; set; }
    }
}
