//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuebleTV
    {
        public int IdMueble { get; set; }
        public int Alto { get; set; }
        public int Largo { get; set; }
        public int Ancho { get; set; }
        public int NumSeparaciones { get; set; }
        public int NumSeparacionesConPuerta { get; set; }
        public int Entrepaños { get; set; }
        public string Color { get; set; }
    
        public virtual Mueble Mueble { get; set; }
    }
}
