//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mueble
    {
        public int IdMueble { get; set; }
        public string Descripcion { get; set; }
        public string Ruta_del_modelo_del_Excel { get; set; }
        public string Ruta_del_modelo_AutoDesk { get; set; }
        public string Ruta_de_una_imagen { get; set; }
        public string TipoMueble { get; set; }
    
        public virtual Closet Closet { get; set; }
        public virtual Lavadero Lavadero { get; set; }
        public virtual Lino Lino { get; set; }
        public virtual MuebleRopas MuebleRopas { get; set; }
        public virtual MuebleTV MuebleTV { get; set; }
        public virtual Vestier Vestier { get; set; }
    }
}
